# 2015.02.05 17:20:53 IST
from thrift.Thrift import *
from ttypes import *
ONEP_VERSION_MAJOR = 1
ONEP_VERSION_MINOR = 3
ONEP_VERSION_MAINTENANCE = 0
ONEP_VERSION_LISP_MAJOR = 0
ONEP_VERSION_LISP_MINOR = 1
ONEP_VERSION_LISP_MAINTENANCE = 0
ONEP_VERSION_VTY_MAJOR = 0
ONEP_VERSION_VTY_MINOR = 1
ONEP_VERSION_VTY_MAINTENANCE = 0
ONEP_VERSION_ONEFW_MAJOR = 0
ONEP_VERSION_ONEFW_MINOR = 1
ONEP_VERSION_ONEFW_MAINTENANCE = 0
ONEP_VERSION_PATHTRACE_MAJOR = 1
ONEP_VERSION_PATHTRACE_MINOR = 0
ONEP_VERSION_PATHTRACE_MAINTENANCE = 0
ONEP_VERSION_CIDB_MAJOR = 0
ONEP_VERSION_CIDB_MINOR = 1
ONEP_VERSION_CIDB_MAINTENANCE = 0
ONEP_VERSION_ADVRTG_MAJOR = 1
ONEP_VERSION_ADVRTG_MINOR = 0
ONEP_VERSION_ADVRTG_MAINTENANCE = 0

# decompiled 1 files: 1 okay, 0 failed, 0 verify failed
# 2015.02.05 17:20:53 IST
